name = "air-monitoring-andijan"
main = "worker.js"
compatibility_date = "2025-10-17"

# KV Namespace для хранения предыдущих данных
[[kv_namespaces]]
binding = "AIR_DATA"
id = "01ebddaaa0ad411c98eeb1556a9e4caf"

# Cron trigger - каждую минуту для тестирования
[triggers]
crons = ["* * * * *"]

# Переменные окружения (будут настроены через Dashboard)
[vars]
# TELEGRAM_BOT_TOKEN = "your-bot-token"
# TELEGRAM_CHAT_ID = "your-chat-id"
