name = "air-monitoring-andijan"
main = "worker.js"
compatibility_date = "2025-10-17"

# KV Namespace для хранения предыдущих данных
[[kv_namespaces]]
binding = "AIR_DATA"
id = "your-kv-namespace-id"  # Замените на реальный ID после создания

# Cron trigger - каждый час на 5-й минуте
[triggers]
crons = ["5 * * * *"]

# Переменные окружения (будут настроены через Dashboard)
[vars]
# TELEGRAM_BOT_TOKEN = "your-bot-token"
# TELEGRAM_CHAT_ID = "your-chat-id"
