name: Air Quality Monitor

on:
  schedule:
    # Тестовый запуск в 23:40, потом вернем на 5-ю минуту каждого часа
    - cron: '40 23 * * *'
    # Запускается каждый час на 5-й минуте (00:05, 01:05, 02:05 и т.д.)
    - cron: '5 * * * *'
  workflow_dispatch:  # Позволяет запустить вручную

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run monitoring script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python monitor.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add previous_data.json || true
        git diff --staged --quiet || git commit -m "Update air quality data [skip ci]"
        git push || true

